# Generated by Django 5.1.7 on 2025-03-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Frutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('classificacao', models.CharField(choices=[('e', 'Extra'), ('p', 'De primeira'), ('s', 'De segunda'), ('t', 'De terceira')], max_length=1)),
                ('fresca', models.BooleanField(default=True)),
                ('quantidade_disponivel', models.PositiveIntegerField()),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
