# Generated by Django 5.1.7 on 2025-03-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frutas',
            name='classificacao',
            field=models.CharField(choices=[('Extra', 'Extra'), ('De primeira', 'De primeira'), ('De segunda', 'De segunda'), ('De terceira', 'De terceira')], max_length=20),
        ),
    ]
