# Generated by Django 5.1.7 on 2025-03-18 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fruits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('desconto', models.PositiveIntegerField(choices=[(5, '5%'), (10, '10%'), (15, '15%'), (20, '20%'), (25, '25%')], default=0)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('fruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruits.frutas')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
